# Generated by Django 4.1.7 on 2023-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=255, verbose_name='Second Name')),
                ('mail', models.EmailField(max_length=255, verbose_name='Email')),
            ],
        ),
    ]
